# Generated by Django 2.0.1 on 2018-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180127_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rwdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
