# Generated by Django 2.0.1 on 2018-01-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Rwdc',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
