# Generated by Django 2.0.1 on 2018-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180127_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name_of_product',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_of_product',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_of_category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Наименование категории'),
        ),
    ]
