# Generated by Django 2.0.2 on 2018-02-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180202_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_of_product',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Наименование товара'),
        ),
    ]
