# Generated by Django 2.0.2 on 2018-02-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180202_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name_of_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Наименование товара'),
        ),
    ]
