# Generated by Django 2.0.2 on 2018-02-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180202_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_of_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Категория'),
        ),
    ]
