# Generated by Django 2.0.2 on 2018-02-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180206_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AddField(
            model_name='image',
            name='name_of_product_image',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product_image',
            field=models.ImageField(upload_to='static/media/goods_image', verbose_name='Изображение'),
        ),
    ]
